services:
  - type: web
    name: goodreads-analyzer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: ALLOWED_ORIGIN
        sync: false
